config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'todos/new', to:'todos#new'
  get 'todos/:id', to:'todos#show' ,as:'todo'
  post 'todos', to: 'todos#create'
  get 'todos', to: 'todos#index' 

  get 'pages/home'
   get 'pages/contact'
  
  get 'about', to: 'pages#about'
  root'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :title, acceptance: { message: 'must be abided' }
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @name = 'Maimona'
  end

  def about
  end

  def contact
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :authenticate_user!, only: [:new]
    def show
    @todo = Todo.find(params[:id])
    end
    def index 
      @todos = Todo.all  
    end
    def new
        @todo = Todo.new
    end
    def create 
        @todo = Todo.new(todo_params)
        if @todo.save
        redirect_to @todo
        else
            render 'new'
        end
    end
    private 
    def todo_params
        params.require(:todo).permit(:title,:completed,:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prometheus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <header>
  <% if user_signed_in? %>
  <p> Welcome <%=  current_user.email %> </p>
  <% end %>
<nav>
<ul>
<li><%= link_to 'Home' , root_path %></li>
<li><%= link_to 'About' , about_path %></li>
<li><%= link_to 'contact' , pages_contact_path %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
<% end %>
</ul>
</nav>
</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome <%= @name %> !</h1>

app/views/todos/_form.html.erb
<h2> New Todo</h2>

<%= form_with model: @todo, local:true  do |form| %>
<p>
Title:
<%= form.text_field :title %>
</p>
<p>
description:
<%= form.text_area :description %>
</p>
<p>
Completed:
<%= form.check_box :completed %>
</p>
<p>
<%= form.submit %>
</p>
<% end %>

app/views/todos/index.html.erb
<h2> ToDo  index</h2>

<% @todos.each do |todo|%>
<div>
<%= todo.id %>
<%= link_to todo.title , todo %>
<%= todo.completed %>
</div>
<% end %>

app/views/todos/new.html.erb
<h2> ToDo  create new </h2>
<% if @todo.errors.any? %>
  <h3>We've got problems!</h3>
 <h4>
  <%= pluralize(@todo.errors.count, 'error') %>
  stopped us from saving the task:
</h4>
<ul>
  <% @todo.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<%= render partial: 'form', locals: {todo:@todo} %>

app/views/todos/show.html.erb
<h2> ToDo </h2>

title: <%= @todo.title %>
<br/>
description: <%= @todo.description %>
<br/>
Completed: <%= @todo.completed %>